### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by alonsopg** [farazfadavi/Sentiment-Analysis#1]
I tried to run this example with:
```

user@MacBook-Pro-de-User:~/Downloads/Sentiment-Analysis-master$ python3 learn.py
Generating word2vec model...
Computing the 'stanford' wordvectors from corpus...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gensim/utils.py", line 495, in save
    _pickle.dump(self, fname_or_handle, protocol=pickle_protocol)
TypeError: file must have a 'write' attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "learn.py", line 500, in <module>
    model = gen_word2vec_model(args.model)
  File "learn.py", line 392, in gen_word2vec_model
    model = compute_word_vectors(DATASET_SENTENCES_FILE)
  File "learn.py", line 416, in compute_word_vectors
    model.save(WORD2VEC_BUILD_FILE)
  File "/usr/local/lib/python3.6/site-packages/gensim/models/word2vec.py", line 1404, in save
    super(Word2Vec, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/gensim/utils.py", line 499, in save
    pickle_protocol=pickle_protocol)
  File "/usr/local/lib/python3.6/site-packages/gensim/utils.py", line 371, in _smart_save
    pickle(self, fname, protocol=pickle_protocol)
  File "/usr/local/lib/python3.6/site-packages/gensim/utils.py", line 924, in pickle
    with smart_open(fname, 'wb') as fout:  # 'b' for binary, needed on Windows
  File "/usr/local/lib/python3.6/site-packages/smart_open/smart_open_lib.py", line 140, in smart_open
    return file_smart_open(parsed_uri.uri_path, mode)
  File "/usr/local/lib/python3.6/site-packages/smart_open/smart_open_lib.py", line 644, in file_smart_open
    return compression_wrapper(open(fname, mode), fname, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'build/wordvectors.bin'
```
Where is the `FileNotFoundError: [Errno 2] No such file or directory: 'build/wordvectors.bin'` file?. Is it a pretrainned vectors file?..

**UPDATE**

Then, I created a bin directory and tried to run again. However, I got:
```

user@MacBook-Pro-de-User:~/Downloads/Sentiment-Analysis-master$ python3 learn.py
Generating word2vec model...
Loading 'stanford' word2vec model from disk...
Traceback (most recent call last):
  File "learn.py", line 501, in <module>
    (vocab_size, feature_size) = model.syn0.shape
AttributeError: 'Word2Vec' object has no attribute 'syn0'

 
```

Which is the correct way of running this example?. Thanks!

**Comment by farazfadavi** [comment]
The word2vec model is developed by google and you need to download it in order to generate the word2vec. Here is their paper [(http://papers.nips.cc/paper/5021-distributed-representations-of-words-and-phrases-and-their-compositionality.pdf)].

**Comment by alonsopg** [comment]
Is there any pretrainned downloadable version?... I checked out the reference, nevertheless the page doesn't work...

**Comment by farazfadavi** [comment]
[wordvectors.bin.zip](https://github.com/farazfadavi/Sentiment-Analysis/files/957023/wordvectors.bin.zip)
From what I read in your error message, I think this is the file you are missing (attached). You need to run clean_data.py before running learn.py. Let me know if this fixes it (plus feel free to star this repository).
